name: Install WordPress
description: Install WordPress locally using WP-CLI.
author: holyhope
branding:
  icon: download-cloud
  color: blue
inputs:
  wordpress_version:
    description: WordPress version
    required: false
    default: latest
  # mysql-version:
  #   description: 'MySQL version'
  #   required: false
  #   default: '5.7'
  php_version:
    description: PHP version
    required: false
    default: '8.2'
  php_extensions:
    description: List of PHP extensions to install
    required: false
    default: imagick
  installation_path:
    description: WordPress Installation path
    required: false
    default: ${{ runner.temp }}/wordpress
  github_token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
  wp_cli_path:
    description: >-
      Path to the WP-CLI binary.

      To use a custom version of WP-CLI, see the [`install-wp-cli`
      GitHub action](https://github.com/marketplace/actions/install-wp-cli)

      Default: Downloaded from the official WP-CLI website.
    required: false
outputs:
  version:
    description: WordPress version
    value: ${{ steps.metadata.outputs.version }}
  path:
    description: Path to WordPress installation
    value: ${{ inputs.installation_path }}
  plugins_path:
    description: Path to WordPress plugins
    value: ${{ steps.metadata.outputs.plugins_path }}
  themes_path:
    description: Path to WordPress themes
    value: ${{ steps.metadata.outputs.themes_path }}
  admin_username:
    description: WordPress admin username
    value: ${{ steps.install.outputs.admin_username }}
  admin_password:
    description: WordPress admin password
    value: ${{ steps.install.outputs.admin_password }}
  db_name:
    description: WordPress database name
    value: wordpress
  db_user:
    description: WordPress database user
    value: root
  db_pass:
    description: WordPress database password
    value: root
  db_host:
    description: WordPress database host
    value: localhost
runs:
  using: composite
  steps:
    - name: Start MySQL
      shell: bash
      run: sudo /etc/init.d/mysql start

    - name: Create the Database
      shell: bash
      run: mysql -e 'CREATE DATABASE wordpress;' -uroot -proot

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        extensions: ${{ inputs.php_extensions }}

    - uses: holyhope/install-wp-cli-github-action@v1.0.0
      id: wp_cli
      if: ${{ ! inputs.wp_cli_path }}

    - name: Download WordPress
      shell: bash
      run: |-
        '${{ inputs.wp_cli_path
          && inputs.wp_cli_path
          || steps.wp_cli.outputs.path
        }}' core download --path=${{ inputs.installation_path }} --force

    - name: Configure WordPress
      shell: bash
      run: >-
        '${{ inputs.wp_cli_path
          && inputs.wp_cli_path
          || steps.wp_cli.outputs.path
        }}' config create \
          --path=${{ inputs.installation_path }} \
          --dbname=wordpress \
          --dbuser=root \
          --dbpass=root

    - name: Install WordPress
      shell: bash
      id: install
      run: |-
        ADMIN_PASSWORD="$( \
          '${{ inputs.wp_cli_path
          && inputs.wp_cli_path
          || steps.wp_cli.outputs.path
        }}' core install \
            --path=${{ inputs.installation_path }} \
            --url=localhost \
            --title=WordPress \
            --admin_user=admin \
            --admin_email='${{ github.actor }}@github.com' \
            --skip-email \
            | sed 's/.*\(http.*\)/\1/' \
        )"
        echo "::add-mask::$ADMIN_PASSWORD"
        cat <<EOF >> "$GITHUB_OUTPUT"
        admin_username=admin
        admin_password=$ADMIN_PASSWORD
        EOF

    - name: Get metadata
      id: metadata
      shell: bash
      run: |-
        cat <<EOF >> "$GITHUB_OUTPUT"
        version=$('${{ inputs.wp_cli_path
            && inputs.wp_cli_path
            || steps.wp_cli.outputs.path
          }}' --path=${{ inputs.installation_path }} core version)
        plugins_path=$('${{ inputs.wp_cli_path
            && inputs.wp_cli_path
            || steps.wp_cli.outputs.path
          }}' --path=${{ inputs.installation_path }} plugin path)
        themes_path=$('${{ inputs.wp_cli_path
            && inputs.wp_cli_path
            || steps.wp_cli.outputs.path
          }}' --path=${{ inputs.installation_path }} theme path)
        EOF
