name: Install WordPress
description: Install WordPress locally using WP-CLI.
author: holyhope
branding:
  icon: download-cloud
  color: blue
inputs:
  wordpress_version:
    description: >-
      Select which version you want to download.
      Accepts a version number, 'latest' or 'nightly'.
    required: false
    default: latest
  wp_cli_version:
    description: >-
      Select which version you want to download.
      Accepts a version number, 'latest' or 'nightly'.
    required: false
    default: latest
  wordpress_title:
    description: The title of the new site.
    required: false
    default: WordPress
  wordpress_locale:
    description: The locale/language for the installation (e.g. `de_DE`).
    required: false
    default: en_US
  # mysql-version:
  #   description: 'MySQL version'
  #   required: false
  #   default: '5.7'
  php_version:
    description: PHP version
    required: false
    default: '8.2'
  php_extensions:
    description: |-
      PHP extensions to install.
      Each extension should be on a new line.
    required: false
    default: |-
      imagick
  installation_path:
    description: WordPress Installation path
    required: false
    default: ${{ runner.temp }}/wordpress
  installation_host:
    description: WordPress Installation host
    required: false
    default: localhost   
  github_token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
  wp_cli_path:
    description: >-
      Path to the WP-CLI binary.

      To use a custom version of WP-CLI, see the [`install-wp-cli`
      GitHub action](https://github.com/marketplace/actions/install-wp-cli)

      Default: Downloaded from the official WP-CLI website.
    required: false
outputs:
  version:
    description: WordPress version
    value: ${{ steps.metadata.outputs.version }}
  path:
    description: Path to WordPress installation
    value: ${{ inputs.installation_path }}
  plugins_path:
    description: Path to WordPress plugins
    value: ${{ steps.metadata.outputs.plugins_path }}
  themes_path:
    description: Path to WordPress themes
    value: ${{ steps.metadata.outputs.themes_path }}
  admin_username:
    description: WordPress admin username
    value: ${{ steps.install.outputs.admin_username }}
  admin_password:
    description: WordPress admin password
    value: ${{ steps.install.outputs.admin_password }}
  db_name:
    description: WordPress database name
    value: ${{ steps.db.outputs.name }}
  db_user:
    description: WordPress database user
    value: ${{ steps.db.outputs.user }}
  db_pass:
    description: WordPress database password
    value: ${{ steps.db.outputs.pass }}
  db_host:
    description: WordPress database host
    value: ${{ steps.db.outputs.host }}
  db_port:
    description: WordPress database port
    value: ${{ steps.db.outputs.port }}
  wp_cli:
    description: Path to WP-CLI binary
    value: >-
      ${{ inputs.wp_cli_path
        && inputs.wp_cli_path
        || steps.wp_cli.outputs.path }}
runs:
  using: composite
  steps:
    - name: Start MySQL
      shell: bash
      run: sudo /etc/init.d/mysql start

    - name: Start Apache
      shell: bash
      run: sudo /etc/init.d/apache2 start

    - name: Create the Database
      shell: bash
      id: db
      run: |-
        USER='wordpress'
        HOST='localhost'
        DATABASE_NAME='wordpress'
        # Generate a random password
        # Use hex to avoid special characters
        PASSWORD="$(openssl rand -hex 12)"

        echo "::add-mask::$PASSWORD"

        echo '::group::Creating database...'

        echo "Creating database '$DATABASE_NAME'"
        mysql --user=root --password=root \
          --execute="CREATE DATABASE $DATABASE_NAME;"

        echo "Creating user '$USER' with password '$PASSWORD'"
        mysql --user=root --password=root \
          --execute="CREATE USER $USER@$HOST
            IDENTIFIED WITH mysql_native_password BY '$PASSWORD';"

        echo "Granting all privileges on '$DATABASE_NAME' to '$USER'"
        mysql --user=root --password=root \
          --execute="GRANT ALL PRIVILEGES ON $DATABASE_NAME.* TO $USER@$HOST;"

        echo '::endgroup::'

        cat <<EOF >> "$GITHUB_OUTPUT"
        name=$DATABASE_NAME
        user=$USER
        pass=$PASSWORD
        host=$HOST
        port=3306
        EOF

    - name: Prepare PHP extensions
      shell: bash
      id: php_extensions
      run: |
        echo -n 'list=' >> "$GITHUB_OUTPUT"
        echo '${{ inputs.php_extensions }}' | tr '\n' ',' >> "$GITHUB_OUTPUT"

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        extensions: ${{ steps.php_extensions.outputs.list }}
      env:
        fail-fast: true
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - uses: holyhope/install-wp-cli-github-action@v1.0.0
      id: wp_cli
      if: ${{ ! inputs.wp_cli_path }}
      with:
        version: '${{ inputs.wp_cli_version }}'
        verify: false

    - name: Download WordPress
      shell: bash
      run: |-
        '${{ inputs.wp_cli_path
          && inputs.wp_cli_path
          || steps.wp_cli.outputs.path
        }}' core download \
          --path='${{ inputs.installation_path }}' \
          --version='${{ inputs.wordpress_version }}' \
          # --skip-content

    - name: Configure WordPress
      shell: bash
      run: >-
        '${{ inputs.wp_cli_path
          && inputs.wp_cli_path
          || steps.wp_cli.outputs.path
        }}' config create \
          --path=${{ inputs.installation_path }} \
          --dbname=wordpress \
          --dbuser=root \
          --dbpass=root

    - name: Install WordPress
      shell: bash
      id: install
      run: |-
        ADMIN_PASSWORD="$( \
          '${{ inputs.wp_cli_path
          && inputs.wp_cli_path
          || steps.wp_cli.outputs.path
        }}' core install \
            --path=${{ inputs.installation_path }} \
            --url='${{ inputs.installation_host }}' \
            --title='${{ inputs.wordpress_title }}' \
            --admin_user='${{ github.actor }}' \
            --admin_email='${{ github.actor }}@github.com' \
            --skip-email \
            --locale='${{ inputs.wordpress_locale }}' \
            | grep 'Admin password: ' \
            | sed 's/Admin password: //' \
        )"

        echo "::add-mask::$ADMIN_PASSWORD"
        cat <<EOF >> "$GITHUB_OUTPUT"
        admin_username=${{ github.actor }}
        admin_password=$ADMIN_PASSWORD
        EOF

    - name: Get metadata
      id: metadata
      shell: bash
      run: |-
        cat <<EOF >> "$GITHUB_OUTPUT"
        version=$('${{ inputs.wp_cli_path
            && inputs.wp_cli_path
            || steps.wp_cli.outputs.path
          }}' --path=${{ inputs.installation_path }} core version)
        plugins_path=$('${{ inputs.wp_cli_path
            && inputs.wp_cli_path
            || steps.wp_cli.outputs.path
          }}' --path=${{ inputs.installation_path }} plugin path)
        themes_path=$('${{ inputs.wp_cli_path
            && inputs.wp_cli_path
            || steps.wp_cli.outputs.path
          }}' --path=${{ inputs.installation_path }} theme path)
        EOF
